version: '3.3'

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=db-fut
      - MYSQL_USER=
      - MYSQL_ROOT_PASSWORD=|K*d&D4u%Gr;No#>
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=|K*d&D4u%Gr;No#>
      - PMA_HOST=mysql
    ports:
      - 8080:80